spring.application.name=user-service

# Подключение к БД
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Ограничение ожидания БД в 5 секунд (чтобы приложение не зависало)
spring.datasource.hikari.connection-timeout=5000

# JPA / Hibernate настройки
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Временно отключаем Liquibase для проверки
spring.liquibase.enabled=true